# .swiftlint.yml
# 25/5/9 이나연

disabled_rules:
  - identifier_name
  - line_length
  - type_name
  - unused_setter_value
  - void_function_in_ternary
  - nesting
  - comment_spacing
  - cyclomatic_complexity

opt_in_rules:
  - function_parameter_count
  - function_body_length
  - trailing_whitespace
  - empty_count
  - empty_string
  - closure_end_indentation
  - let_var_whitespace
  - sorted_imports
  - trailing_newline

excluded:
  - TODOMate/App/AppDelegate.swift
  - TODOMate/App/SceneDelegate.swift
